//
//  AnimatedMeshGradientView.swift
//  ImagePromptsOrganizer
//
//  Created by Aashish Patil on 10/23/25.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by Google Search AI Mode

import SwiftUI

struct AnimatedMeshGradientView: View {
    var body: some View {
        TimelineView(.animation) { timeline in
            let time = timeline.date.timeIntervalSince1970
            let xOffset = 0.5 + sin(time) * 0.35
            let yOffset = 0.5 + cos(time) * 0.45
            
            MeshGradient(
                width: 3,
                height: 3,
                points: [
                    [0, 0], [0.5, 0], [1, 0],
                    [0, 0.5], [Float(xOffset), Float(yOffset)], [1, 0.5],
                    [0, 1], [0.5, 1], [1, 1]
                ],
                colors: [
                    .purple, .blue, .purple,
                    .pink, .yellow, .pink,
                    .purple, .blue, .purple
                ]
            )
            .ignoresSafeArea()
        }
    }
}
