// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftUI

// generated by AIMode in Google Search
struct AdvancedZoomableImage: View {
    @State private var totalScale: CGFloat = 1.0
    @State private var magnifyBy: CGFloat = 1.0

    @State private var totalOffset: CGSize = .zero
    @State private var gestureOffset: CGSize = .zero
    
    @State var displayImage: UIImage
    
    var body: some View {
        Image(uiImage: displayImage)
            .resizable()
            .scaledToFit()
            .scaleEffect(totalScale * magnifyBy)
            // Fix applied here: Add width and height individually
            .offset(x: totalOffset.width + gestureOffset.width,
                    y: totalOffset.height + gestureOffset.height)
            .gesture(
                MagnifyGesture()
                    .onChanged { value in
                        magnifyBy = value.magnification
                    }
                    .onEnded { value in
                        totalScale *= magnifyBy
                        magnifyBy = 1.0
                    }
                    .simultaneously(with: DragGesture()
                        .onChanged { value in
                            gestureOffset = value.translation
                        }
                        .onEnded { value in
                            totalOffset.width += value.translation.width
                            totalOffset.height += value.translation.height
                            gestureOffset = .zero
                        }
                    )
            )
    }
}

